apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: unseal.vault.io
spec:
  scope: Namespaced
  group: vault.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: exporterDockerImage
          type: string
          priority: 0
          jsonPath: .spec.auto-unseal-image
          description: Vault auto unseal full image url
        - name: VaultSecretName
          type: string
          priority: 0
          jsonPath: .spec.vault-root-token
          description: Vault root token
  names:
    kind: unseal
    plural: unseal
    singular: unseal
    shortNames:
      - un
